### ISSUE TITLE
Confusion matrix should support segmentation

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#1130]
**Is your feature request related to a problem? Please describe.**
Currently, the confusion matrix metric can only support classification task, if doing segmentation, it needs to accumulate all the outputs of 1 epoch and compute, it will cause out of memory.
Need to compute the 4 elements of every image and compute final results when epoch completed.

**Comment by wyli** [comment]
Hi @Nic-Ma are you referring to the ignite handler merged earlier today https://github.com/Project-MONAI/MONAI/pull/1128?  this ticket is a bit confusing because the metric computation part actually support segmentation already https://github.com/Project-MONAI/MONAI/blob/3adee016f6ce522176f7bbaeef11231959677e89/monai/metrics/confusion_matrix.py#L34

**Comment by Nic-Ma** [comment]
Hi @wyli ,

In current implementation of confusion matrix, it needs to accumulate segmentation results of the whole epoch and compute, which will cause `out of memory` easily, I suppose to do `update` logic after every iteration, similar to the `MeanDice` metric we have.

Thanks.

**Comment by Nic-Ma** [comment]
@yiheng-wang-nv already fixed this issue.
Thanks.
