### ISSUE TITLE
SplitChannels transform

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1219]
**Is your feature request related to a problem? Please describe.**
a splitchannel transform is needed in order to preprocess each subset of channels separately.

**Describe alternatives you've considered**
the current implementation only works as a post-processing module

**Additional context**
https://github.com/Project-MONAI/MONAI/blob/4e9164032610b69acdf716765909f5ec393af36a/monai/transforms/post/array.py#L29-L34

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Sounds interesting a feature request.
I will do below steps to support it:
1. Remove the `to_onehot` operation in the existing `SplitChannel` transform, because we unified to use `post_transform` for these logic now.
2. Add a `SplitChannel` transform in utilities category, it contains logic to `to_onehot` and `split_channel` based on numpy data.
What do you think?

Thanks.

**Comment by wyli** [comment]
I don't think SplitChannel should ever contain the to_onehot logic. the rest of the steps looks good to me. @Nic-Ma

**Comment by Nic-Ma** [comment]
Hi @wyli ,

So do you prefer to add a `to_one_hot` API for numpy data? Or enhance existing `to_one_hot` API to be compatible with both numpy and Tensor and support specified `channel_dim`?

Thanks.

**Comment by wyli** [comment]
by existing to_one_hot API do you mean AsDiscrete? perhaps we can have another ticket about it after we remove to_one_hot from splitchannel? this ticket is about split multichannel data into multiple data items
