### ISSUE TITLE
docker image build fails frequently

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1252]
**Describe the bug**
recently the docker image build on DockerHub fails frequently without specific error msg:
![Screenshot 2020-11-17 at 12 10 07](https://user-images.githubusercontent.com/831580/99388822-0eb44000-28ce-11eb-8fb1-bd4f95ddbb96.png)
this might due to longer building time or larger disk space requirement, need some investigations here.

**Additional context**
https://hub.docker.com/repository/docker/projectmonai/monai/builds

**Comment by IsaacYangSLA** [comment]
The same docker build process took about 4 minutes in build_only runner (https://github.com/Project-MONAI/MONAI/runs/1413950455?check_suite_focus=true).  If docker hub has computation/memory quota, we can remove the build process used in docker hub and add a `docker push` to dockerhub when the local_docker step is finished.  Since both docker hub and local_docker build the image from Dockerfile, the resulting container images will be the same.

**Comment by wyli** [comment]
that sounds great @IsaacYangSLA, thanks! could you send a PR to extend the local docker step? perhaps could incorporate the changes in #1253 if they are useful.

the webhook will also trigger build for a tagging push (for milestone releases), so for now let's not completely cancel the webhook

**Comment by danielschulz** [comment]
> The same docker build process took about 4 minutes in build_only runner (https://github.com/Project-MONAI/MONAI/runs/1413950455?check_suite_focus=true). If docker hub has computation/memory quota, we can remove the build process used in docker hub and add a `docker push` into our CI script after the local_docker step is finished. Since both docker hub and local_docker build the image from Dockerfile, the resulting container images will be the same.

I basically just did that to solve the issue w/ rate limits on hub.docker.com. Here's my PR:
[#1406 ](https://github.com/Project-MONAI/MONAI/pull/1406)

That's how I'd solve the issue:
https://github.com/Project-MONAI/MONAI/pull/1406/files#diff-2b7a275119830a358bfee2c8a847ea3d1f46f4e2ad8e6239e76d60275e322021
