### ISSUE TITLE
MetricsSaver Bug when filename is long

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/MONAI#1633]
**Describe the bug**
When using the `MetricsSaver` handler, a list of filenames will be joined as a string first (see [here](https://github.com/Project-MONAI/MONAI/blob/master/monai/handlers/metrics_saver.py#L111)), and then send to write the metric report.

In distributed mode, the way to join all filenames into a string is directly connect all filenames by the setted delimiter (see [here](https://github.com/Project-MONAI/MONAI/blob/db2dbb07379e3dff47777fef8c9ac66671457916/monai/handlers/utils.py#L88)), and all filenames need to be gathered via ignite's `all_gather` function first. However, this method has a limitation that if the length of the string to be gathered is larger than 1024, the string will be truncated and only keep the first 1024 characters (the ignite source code of this function is in [here](https://github.com/pytorch/ignite/blob/master/ignite/distributed/comp_models/base.py#L90)).

Therefore, if the filename string is truncated, the number of metrics will be different from the number of filenames.

It is usual to get a larger than 1024 length string, for instance, a filename on my current working dataset is:
`'/workspace/data/medical/Task04_Hippocampus/imagesTr/hippocampus_033.nii.gz'` that has the length 74, thus more than 14 samples will introduce the bug.

Hi @Nic-Ma @wyli , we may need to modify the metric saving way, and avoid gathering the string (tensor or float types do not have the limitation, see [here](https://github.com/pytorch/ignite/blob/master/ignite/distributed/comp_models/base.py#L142)). What do you think?

**Comment by vfdev-5** [comment]
@Nic-Ma thanks for pinging !

Well, the limitation of 1024 is artificial and was done in a way to pad data into a fixed size tensor. In case of MetricsSaver, maybe, it is better to collect names one by one in order to avoid going over 1024 chars.

> It is usual to get a larger than 1024 length string, for instance, a filename on my current working dataset is:
'/workspace/data/medical/Task04_Hippocampus/imagesTr/hippocampus_033.nii.gz' that has the length 74, thus more than 14 samples will introduce the bug.

@yiheng-wang-nv I do not quite understand your point here. Filepath is 74 chars which is far smaller than 1024, right ?
I think also there is a max path lenght on unix systems, like 256 chars ... to check that.

Anyway, @yiheng-wang-nv thanks for reporting that. I think, we can also think about on how to fix this issue from ignite side as well.

**Comment by Nic-Ma** [comment]
Hi @vfdev-5 ,

Thanks for your help here, hopefully you guys will update it in ignite 0.5.
In order to fix it in MONAI first, I submitted a PR: https://github.com/Project-MONAI/MONAI/pull/1634.

Thanks.

**Comment by vfdev-5** [comment]
I think we'll do another 0.4.4 release with few bug fixes next week...

**Comment by Nic-Ma** [comment]
> I think we'll do another 0.4.4 release with few bug fixes next week...

Cool, sounds great.
We will also update ignite dependency in MONAI v0.5 release soon.

Thanks.

**Comment by vfdev-5** [comment]
MONAI versions are going quickly :) That's great !
