### ISSUE TITLE
How to open dicom with LoadImage() from Tempfile

### ISSUE THREAD

**Issue by tugot17** [Project-MONAI/MONAI#1656]
I have a web api in which I want to analyze dicom images. It is defined using FastAPI 

The method that gets dicom is defined like this:

```python
@analyze_my_dicom.post("/analyze_my_dicom")
async def analyze_my_dicom(dicom: UploadFile = File(...)):
    
    filename = join(
        dirname(realpath(__file__)), "dicoms", dicom.filename
    )

    try:
        with open(filename, "wb") as buffer:
            shutil.copyfileobj(dicom.file, buffer)

        transform = LoadImaged(keys="image")
        data = {"image": filename}
        image = transform(data)["image"]
        ...
```

Is there a possibility to use `LoadInaged` directly on `UploadFile`, so I don't have to save the object to the memory but can work with it directly?

**Comment by wyli** [comment]
perhaps the `NumpyReader` option of the LoadImage could already support loading from file-like object like `UploadFile` in this case https://github.com/Project-MONAI/MONAI/blob/master/monai/data/image_reader.py#L476 but the data should be converted into numpy format beforehand...

otherwise I'm not sure whether ITK reader supports/will support this cc @thewtex

**Comment by thewtex** [comment]
The ITK reader talks to the filesystem, so a path to explore is to [present the data virtually on the filesystem with FUSE](https://github.com/fusepy/fusepy/blob/master/examples/memory.py).
