### ISSUE TITLE
Rand3DElastic doesn't provide a spacing option

### ISSUE THREAD

**Issue by WinterPan2017** [Project-MONAI/MONAI#1816]
Why can't I set spacing when I use Rand3DElastic?  I noticed that RandDeformGrid is not used in the source code. Could you please tell me the reason?

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Could you please help share some info on this question?

Thanks in advance.

**Comment by wyli** [comment]
thanks for raising this issue. Rand2DElastic has a spacing option, but that's not currently implemented in 3D. The reason is that the 3D elastic deformation is implemented with an approximation using Gaussian smoothing of the displacement field. The root cause is that the upsampling of the 3D displacement field using high order interpolations (https://github.com/Project-MONAI/MONAI/issues/789) is not currently supported by PyTorch.
