### ISSUE TITLE
CI/CD Pipeline setup

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#19]

**Comment by atbenmurray** [comment]
Our BMEIS policy has been GitLab CI/CD for GitHub. It allows first class GPU support for test agents

**Comment by atbenmurray** [comment]
We have been using 'GitLab CI/CD for GitHub' as it comes with full GPU test agent support. Shall we just go with that?

Let's protect master so that it can only be updated via PR.

Github provides 'auto-squash' option on PRs so that they are always a single commit on master. This is good because it keeps master history clean. I'd go further and suggest rewriting commit message for the PR so that it summarises the feature.

Re checks, we should be able to configure CI so that testing happens automatically on PR submission (i.e. before it has been passed/merged). All unit and integration tests should be run on a CI basis, ideally.

We can have a nightly build. We may wish to have longer running training tests that execute on it. It is a bit tricky given the unstable nature of some networks, however.

Notification of the team; I guess you mean automatic emails; don't we get them from the issues, updates to the issues? If not, I guess that there is a hook of some kind.

**Comment by wyli** [comment]
Thanks @atbenmurray, just to confirm that now the master can only be updated via PR, squash merging is enabled for PR.
