### ISSUE TITLE
Set up CI/CD for JIT extension packaging/release

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1994]
**Is your feature request related to a problem? Please describe.**
follow up of PR #1802, CI/CD should be updated to support the packaging and release of the new features https://github.com/Project-MONAI/MONAI/pull/1802#issuecomment-814838242

**Comment by charliebudd** [comment]
I think the issue is not the coverage of the JIT extention. I've included unit tests for the GMM algorithm which would fail if the JIT system had issues. Really the problem is that the pypi process is not covered, and this isnt such a simple fix. 

Currently our unit tests workflow checks out the incoming branch. While this works, it isn't how most users will get MONAI and means it hasnt gone through the pypi proccess. Seems like we could improve this by pip installing from the incoming branch before running the tests. In the git workflow yaml, this would look like this...

`pip install git+https://github.com/${{ github.repository }}.git@${{ github.ref }}`

However this doesn't include the unit tests as they aren't kept in the monai directory. One way this could work is to use pypi's  [testing process](https://python-packaging.readthedocs.io/en/latest/testing.html) (this still would require moving the unit tests into the monai directory). To run tests locally the command would then be...

`python setup.py test`

This then means we can run this command in our git workflow...

`pip install --install-option test git+https://github.com/${{ github.repository }}.git@${{ github.ref }}`

This would be quite the departure from the current method of doing things, and I'm sure some will be more well versed in this area than I. Maybe we should discuss this in the weekly meeting? In the mean time I can start to get a PR togther if we think its potentially the way we should go? If we decide its a goer It would probably be good to integrate this with the gitflow change we have coming up @ericspod?

After writing all of this I discovered [tox](https://tox.readthedocs.io/en/latest/#what-is-tox) which looks like it could handle alot of this quite nicely. As I've suggested above it runs tests on the package after the packaging process so it would at least fix this issue, and potential smoothing some things out in the long run, but might take some setting up.

**Comment by wyli** [comment]
we have some basic package tests for  pip install commands and `min_tests` every time we release a milestone version on PyPI https://github.com/Project-MONAI/MONAI/blob/master/.github/workflows/release.yml#L34-L63 perhaps we could make it nightly and extend the coverage

**Comment by charliebudd** [comment]
Would it not make sense to pip install monai like in release.yml for the normal PR workflow?

**Comment by ericspod** [comment]
In our workflow we can install MONAI however we like but we can also clone the repo locally and run the tests that we pull down. I think we do need to discuss this at the next meeting and work out how this will fit in with the gitflow migration. Our CI/CD pipeline is going to change somewhat for this regardless.
