### ISSUE TITLE
Random Intensity transforms for test-time augmentation

### ISSUE THREAD

**Issue by han-liu** [Project-MONAI/MONAI#2213]
Hi,

Test-time augmentation is a helpful tool to use but it seems that currently only spatial transformations are included for TTA. Intensity transformations such as Random contrast are not invertible transforms and thus cannot be used in current TTA implementation. Is there a way that I can use intensity transforms as TTA? Thanks.

**Comment by han-liu** [comment]
@rijobro @tvercaut Thanks for the clarification and I think what @tvercaut proposed here is a great feature to be added to TTA.

**Comment by rijobro** [comment]
@tvercaut to take the example of `GaussianNoise`, the inverse of the spatial component of that transform is identity, because obviously adding Gaussian noise doesn't modify the image spatially. Having said that, I think it would be complicated for us to therefore say that a pseudo of the inverse can be given as identity. Because at that point, we're saying that the most important component of the inverse is the spatial component. This may or may not be true, but I'm not sure we really want to make a decision either way. 

A potential solution might be to have something like:

```python
def inverse(self, x):
    x = self.spatial_inverse(x)
    x = self.intensity_inverse(x)
    # any other types of inverse
    ...
```
But I think this starts to get messy and is probably overkill for what we want. And no, we don't have different inverses depending on the network type.
