### ISSUE TITLE
Add utility to be able to retrieve MMAR ts/pt relative path from MMAR model id

### ISSUE THREAD

**Issue by aihsani** [Project-MONAI/MONAI#2512]
**Is your feature request related to a problem? Please describe.**
When using [`load_from_mmar`](https://github.com/Project-MONAI/MONAI/blob/0.6.0rc1/monai/apps/mmars/mmars.py#L179) there is no utility to find where the model pt/ts file is located when it is needed (e.g. for training).

**Describe the solution you'd like**
It would be great if [`_get_model_spec`](https://github.com/Project-MONAI/MONAI/blob/2085a49820be146ad953ece23041540a237e08b6/monai/apps/mmars/mmars.py#L36) were either made available for import or there was a utility where one can pass the MMAR id and get the relative model path.

**Comment by Nic-Ma** [comment]
Hi @aihsani ,

Thanks for your feature request.
I created PR: https://github.com/Project-MONAI/MONAI/pull/2515 to make `get_model_spec` as an API.

Thanks.

**Comment by wyli** [comment]
Before implementing this feature request, we need more discussions here…

The idea of the MONAI MMAR module is to make the MMAR available as pytorch/monai objects, so that the pretrained models can be easily integrated into any existing pytorch/monai code. The goal is to decouple the underlying MMAR implementation details from the MONAI applications.

So, properties such as model json config/fetching remote files/local mmar caching path, should be maintained by MONAI internally. We may change them according to the NGC/Clara train software updates. MONAI end users shouldn't worry about the MMAR low-level implementation details.

cc @SachidanandAlle
