### ISSUE TITLE
dimension error when using AsDiscrete function to do make_one_hot

### ISSUE THREAD

**Issue by tangzhe0220** [Project-MONAI/MONAI#2549]
**Describe the bug**
dimension error when using AsDiscrete function to do make_one_hot

**To Reproduce**
1. Go to 'monai/transforms/post/array.py'
2. set a tensor with size [N, C, width, height, depth]
3. call AsDiscrete(to_onehot=True, n_classes=class_nums)(tensor), then error occurs
4. in  the file 'monai/transforms/post/array.py' line 172, the code is: img = one_hot(img, num_classes=_nclasses, dim=0), why set dim=0? if the input img has dimensions as [B]1[spatial_dims], parameter 'dim' should be set as 1, I think.

**Screenshots**
![image](https://user-images.githubusercontent.com/20511588/124789543-f720e900-df7c-11eb-936e-6d96a7c85533.png)

**Comment by Nic-Ma** [comment]
Hi @tangzhe0220 ,

Thanks for your issue report.
Actually, this is expected behavior of MONAI v0.6 that we changed all the postprocessing transforms to handle `channel-first` data. So please decollate the batch data first.
You can refer to this tutorial: https://github.com/Project-MONAI/tutorials/pull/251

Thanks.
