### ISSUE TITLE
No Post-processing Without Decollate!

### ISSUE THREAD

**Issue by behxyz** [Project-MONAI/MONAI#2571]
**Describe the bug**
https://github.com/Project-MONAI/MONAI/blob/3edff7449984f87c371ac87c99244e6b00e97a92/monai/engines/workflow.py#L167-L171

Not all the metrics accepting decollated tensors, for instance `ignite.metrics.Accuracy` expects individual tensors, so disabling the entire post-processing transformation when `decollate=False` is limiting and in fact it has broken the pathology pipeline.

**Expected behavior**
The post-processing being applied regardless of `decollate` status.

**Comment by wyli** [comment]
Agreed, I feel we shouldn't have this restriction at the workflow level, any idea why is it introduced?

Could you please help log the pathology pipeline bug in detail in a separate ticket? All the integration tests passed, we were not aware of the issue.

**Comment by Nic-Ma** [comment]
Hi @behxyz ,

Thanks for your issue report.
May I know your ignite version? All the ignite metrics support `list of tensors` **since v0.4.5**, the optional import in MONAI is ">= 0.4.4" as we discussed here: https://github.com/Project-MONAI/MONAI/pull/2451.

@wyli , currently, we suppose all the post-processing transforms work with `channel-first` tensor, I think we should not apply them if `decollate=False` because the data shape doesn't match at all.
I think maybe we can change the logic to: (1) always decollate batch and apply postprocessing transforms, (2) change the arg `decollate` to `collate`, if `collate=True`, try to collate the result of postprocessing back to `batch-first` tensor for the following tasks, what do think?
For most of the cases, I think the current solution works fine.

Thanks.

**Comment by Nic-Ma** [comment]
BTW, `ignite.metrics.Accuracy` is already covered in the integration test:
https://github.com/Project-MONAI/MONAI/blob/dev/tests/test_integration_workflows.py#L148

CC @rijobro @ericspod @vfdev-5 .

Thanks.

**Comment by wyli** [comment]
Thanks for the reply @Nic-Ma  let's track pathology pipeline bugs in a separate ticket if there's any...

For the main topic here, the postprocessing's type is a generic `Optional[Callable]` (instead of `monai.transforms.Transform`)
https://github.com/Project-MONAI/MONAI/blob/3edff7449984f87c371ac87c99244e6b00e97a92/monai/engines/workflow.py#L98
we should keep this flexibility throughout the base workflow implementation. The decollate can be viewed as a slightly special postprocessing step at this workflow level.

For the workflow flexibility, I have another two comments,
(1) for `on(IterationEvents.MODEL_COMPLETED)` of the monai engine, the user should be able to set a sequence of event handlers in an arbitrary order, for example: "MyEventHandler1 -> Decollate -> MyEventHandler2 -> MyEventHandler3", in this way the workflow allows for some customised event handling before the decollate. But by default, we could provide `Decollate -> monai.handlers.Postprocessing -> any user specified handlers`.
Might be good to have a `Decollate` handler?

(2) I think the postprocessing logic is also too restrictive:
https://github.com/Project-MONAI/MONAI/blob/3edff7449984f87c371ac87c99244e6b00e97a92/monai/engines/workflow.py#L196-L201
https://github.com/Project-MONAI/MONAI/blob/3edff7449984f87c371ac87c99244e6b00e97a92/monai/handlers/postprocessing.py#L54-L58

both case should be changed to something like:
```py
def _run_postprocessing(engine: Engine) -> None:
    if not isinstance(engine.state.batch, list) or not isinstance(engine.state.output, list):
        warnings.warn("postprocessing requires `engine.state.batch` and `engine.state.outout` to be lists.")
        engine.state.batch, engine.state.output = engine_apply_transform(engine.state.batch, engine.state.output, transform)
    else:
        for i, (b, o) in enumerate(zip(engine.state.batch, engine.state.output)):
            engine.state.batch[i], engine.state.output[i] = engine_apply_transform(b, o, posttrans)
```

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for your suggestions and comments, makes sense to me.
Actually, I think we have discussed this topic several times before, and at that time our data shape is not flexible and also need to consider the `TransformInverter` and `Metrics` a lot, but now we don't have those restrictions anymore.
So I made an enhancement proposal based on our current implementation and your suggestions:
1. `_run_postprocessing` always executes no matter `decollate=True / False`.
2. Enhance `_run_postprocessing` to run `engine_apply_transform` directly if not both `batch` and `output` are lists, so it can also support other postprocessing methods instead of MONAI transforms.
3. Develop a `DecollateBatch` handler, so users can set `decollate=False` in the trainer and do some other logic then decollate the data in handlers, just a similar idea as the `Postprocessing` handler.

I can implement this proposal ASAP, what do you think?

Thanks.

**Comment by wyli** [comment]
Thanks, sounds good @Nic-Ma, please help keep the PR simple in case that we cherry pick it for a minor version release in the near future...

**Comment by Nic-Ma** [comment]
@wyli , Sure, I will try to make 2 or 3 small and independent PRs for this ticket.

Thanks.

**Comment by behxyz** [comment]
> BTW, `ignite.metrics.Accuracy` is already covered in the integration test:
> https://github.com/Project-MONAI/MONAI/blob/dev/tests/test_integration_workflows.py#L148
> 
> CC @rijobro @ericspod @vfdev-5 .
> 
> Thanks.

Thank you @Nic-Ma! It solved the issue with pathology pipeline.  In the previous version of MONAI, `from_engine` was not needed to extract "pred" and "label", and a lambda function was working before, which doesn't work now. Have we documented this change anywhere?

**Comment by ericspod** [comment]
> 
> 
> > BTW, `ignite.metrics.Accuracy` is already covered in the integration test:
> > https://github.com/Project-MONAI/MONAI/blob/dev/tests/test_integration_workflows.py#L148
> > CC @rijobro @ericspod @vfdev-5 .
> > Thanks.
> 
> Thank you @Nic-Ma! It solved the issue with pathology pipeline. In the previous version of MONAI, `from_engine` was not needed to extract "pred" and "label", and a lambda function was working before, which doesn't work now. Have we documented this change anywhere?

This wasn't mentioned in release notes or in the 0.6.0 highlights I don't think. We might want a section in release notes on minor changes like this that affect the API.

**Comment by Nic-Ma** [comment]
Hi @behxyz and @ericspod ,

We prepared detailed description about the changes in the wiki page:
https://github.com/Project-MONAI/MONAI/wiki/v0.5-to-v0.6-migration-guide

Thanks.

**Comment by ericspod** [comment]
Ah yes I missed that sorry, it's something to link in release notes if we have changes like this again in the future.

**Comment by Nic-Ma** [comment]
> Ah yes I missed that sorry, it's something to link in release notes if we have changes like this again in the future.

Hi @ericspod ,

Sure, and is the wiki page public access? If yes, I can make a quick PR to add the link to our current `What's new in 0.6` page.
People will see it when open MONAI dev branch instead of v0.6.0 branch.

Thanks.

**Comment by ericspod** [comment]
The wiki is all public, so yes please add it to "What's new" and also the [release notes for 0.6.0](https://github.com/Project-MONAI/MONAI/releases/tag/0.6.0). Thanks!

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

Sure, I submitted PR: https://github.com/Project-MONAI/MONAI/pull/2585 for your review.

Thanks.
