### ISSUE TITLE
hosting data and pretrained models

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#271]
**Is your feature request related to a problem? Please describe.**
for data and model released under project-monai, would be great to host them via a separate GitHub repo within the organisation scope https://github.com/Project-MONAI

**Describe the solution you'd like**
- creating new repo(s) 
- setup licencing information
- define scripts (preferably in python) for users to download the contents

this is a follow-up of https://github.com/Project-MONAI/MONAI/pull/263 
related https://github.com/Project-MONAI/MONAI/issues/237 https://github.com/Project-MONAI/MONAI/issues/88 https://github.com/Project-MONAI/MONAI/issues/87

**Comment by jenspetersen** [comment]
Transferring discussion from #297 to here (@Nic-Ma @vfdev-5)...

It is highly desirable to have something akin to torchvision.datasets for medical datasets, so that we can `from monai.datasets import XYZ`. Benefits:
- easy
- improves reproducibility
- probably more :)

@Nic-Ma I don't think we necessarily need to host data ourselves, I think we should rather pull from official sources (like torchvision, if I'm not mistaken).

This was discussed in the first meeting of the benchmarking working group and I believe there is a general consensus that we need this feature. The main issue being raised was that it's non-trivial to decide which datasets to include, but I personally think that we should just start with a few obvious ones (medical decathlon, ...), continuously integrate new ones, hopefully gain momentum, define best practices for dataset hosting, format etc. that people can follow and eventually have people make PRs to add their data to monai.

**Comment by Nic-Ma** [comment]
Hi @jenspetersen ,

About hosting dataset, it's because some datasets are on GoogleDrive or some storage that are not easy to download by commands and may have network access restrictions for users(May need to register account or need VPN).
Anyway, I agree to wait for the discussion from working group meetings first.

Thanks.

**Comment by jenspetersen** [comment]
There's nothing wrong with hosting data ourselves, it's just more work and might cost a little money :)

**Comment by wyli** [comment]
fixed by starting https://github.com/Project-MONAI/model-zoo
