### ISSUE TITLE
MONAI docker 0.7.0 seems wrong

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/MONAI#3018]
When run `docker pull projectmonai/monai:0.7.0`, the pulled image is the same as 0.6.0

https://hub.docker.com/r/projectmonai/monai/tags?page=1&ordering=last_updated

![Screen Shot 2021-09-24 at 12 25 53 PM](https://user-images.githubusercontent.com/68361391/134618117-98da8cf8-0e18-48cf-b59a-25f4f7447635.png)

![Screen Shot 2021-09-24 at 12 25 18 PM](https://user-images.githubusercontent.com/68361391/134618072-26e60adf-ce2e-4bce-bd90-15e9fcbef3a3.png)
)

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Could you please help confirm this issue? Maybe the pushed content is not correct?

Thanks in advance.

**Comment by wyli** [comment]
Thanks for reporting, this is now rectified. The root cause is that we changed to release the milestone from "main" since 0.6 https://github.com/Project-MONAI/MONAI/blob/aa4eb5ddc2e2cd435617ee5fc3de2fc30cf7bc77/.github/workflows/release.yml#L125
I'll enhance the release pipeline to avoid similar issues in the future.
