### ISSUE TITLE
Could use "DHW" dimension order with ITKReader?

### ISSUE THREAD

**Issue by 7oud** [Project-MONAI/MONAI#3021]
**Is your feature request related to a problem? Please describe.**
There are different data storing order in Nibabel and ITK, `WHD` in Nibabel and `DHW` in ITK, Now MONAI uses the only dimension order `WHD` both with nibabel reader and ITK reader, paritcularly do data transpose in ITKReader. However, when using MONAI trained model in C++ with ITK library, addtiional transposes are needed, It's terrible and `WHD` order is not optimal performance.

**Describe the solution you'd like**
Could choose different dimension order when using Nibabel or ITKReader?

**Comment by wyli** [comment]
The LoadImage transforms also support customised readers. Would it be feasible to extend the ITK reader to handle this spatial convention? 

Also, I think itk returns a view instead of actually allocates a new array for the transpose https://blog.kitware.com/convert-itk-data-structures-to-numpy-arrays/ any chance that we can make the transpose cheap by simply changing the view cc @thewtex

**Comment by wyli** [comment]
This is somewhat related to #2891 perhaps we should consolidate the discussions.

**Comment by 7oud** [comment]
If using customised readers, can the transforms work correctly, such as `monai.transforms.Spacing`?

**Comment by wyli** [comment]
yes, it'll work as long as these properties are defined: https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/image_reader.py#L233-L240

**Comment by wyli** [comment]
thanks for the comment, [this pull request](https://github.com/Project-MONAI/MONAI/pull/3508) adds a `reverse_indexing` option to `ITKReader`. Models trained with `reverse_indexing=True` should be compatible with the ITK c++ spatial indexing convention.
