### ISSUE TITLE
Interpretability of Segmentation UNet

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#3032]
### Discussed in https://github.com/Project-MONAI/MONAI/discussions/3005

<div type='discussions-op-text'>

<sup>Originally posted by **joho84** September 22, 2021</sup>
Hi!
First of all, thank you very much for your work and the great support you offer!
I have a question concerning the interpretability of a segmentation Unet. I am trying to get some more insight into the functioning of my Unet trained on multi-channel data. In especially I would be interested in which channels and which voxels contribute the most to the decision of the trained Unet for the segmentation of a specific class. Something similar to this: https://arxiv.org/abs/2002.11434
Is there already a way to achieve this in monai? Or could you point me in the right direction to adapt the existing interpretability code to a segmentation task?
Thank you in advance!</div>

(converting the discussion into a feature request)
see also https://github.com/kiraving/SegGradCAM

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

I think you are expert on the UNet, could you please help share some comments?

Thanks in advance.

**Comment by ericspod** [comment]
I'm afraid I don't have much experience with this specific sort of interpretability. @rijobro already weighed in about gradcam and what we've done with it, but for this problem you're looking at discerning the contribution of specific parts of the input not just regions. I could guess at a few strategies to try which aren't specific in any way to what network you have. Adding noise to one channel at a time to see what causes performance to decrease the most during inference, or even blacking out a channel, applying occlusion mapping to one channel at a time (occlusion is like noise), etc. Essentially making one channel worse so that it's contribution is decreased to the final result. If the channels are co-dependent this might be hard to see in which case you'd have decreasing performance no matter which channel you attack, then it could be argued all channels are equally important.
