### ISSUE TITLE
CacheDataset would benefit greatly from multithreaded processing

### ISSUE THREAD

**Issue by hjmjohnson** [Project-MONAI/MONAI#309]
**Is your feature request related to a problem? Please describe.**
I have access to huge amounts of medical imaging data (20,000 3D scans), and very large many core computer (88 hyperthreaded CPU's).

The pre-preocessing step to generate the initial cache is currently single threaded, so building up the initial cache is taking much longer than expected.

**Describe the solution you'd like**

I think that supporting multi-threading for applying the initial transorms would be a huge benefit to testing.

```python
CacheDataset(data=val_files, transform=val_transforms, cache_rate=1.0)

##
CacheDataset(data=val_files, transform=val_transforms, cache_rate=1.0, num_workers=88)
##---------------------------------------------------------------------^^^^^^^^^^^^^^^^^^
```
**Additional context**
After looking at the DataLoader interface for implementing  `num_workers`, I realized that this may not be as trivial of a task as I expected.

**Comment by Nic-Ma** [comment]
Hi @hjmjohnson ,

Thanks very much for raising this topic!
Actually, we already discussed it internally before, it's a very important enhancement for our CacheDataset mechanism. Due to schedule, I didn't add multi-thread support for v0.1.0 release.
Would you like to submit a PR for `num_threads` feature if you have time?
Of course, if you are not available, I can also try to implement it several weeks later when I finished existing tasks.
Thanks in advance.
