### ISSUE TITLE
RuntimeError - Transform 

### ISSUE THREAD

**Issue by HripsimeS** [Project-MONAI/MONAI#3816]
Dear MONAI community,

I am trying to test the following notebook for 3D Unet segmentation
https://github.com/Project-MONAI/tutorials/blob/master/3d_segmentation/spleen_segmentation_3d_lightning.ipynb

On the stage of "Run the training", the process is interrupting in the middle with following error message "RuntimeError: applying transform <monai.transforms.spatial.dictionary.Spacingd object at 0x0000019CAC2BB970>". I tried to reduce "num_workers" and "batch_size", but it did not help. Can you please provide some solution for this error/bug. 

Look forward to hearing from you.

**Comment by wyli** [comment]
it seems it works fine with the google colab (with a gpu runtime) https://colab.research.google.com/github/Project-MONAI/tutorials/blob/master/3d_segmentation/spleen_segmentation_3d_lightning.ipynb, so it's probably your local environment issue, I'm converting this into a discussion. please follow the issue reporting template with more details so that we might be able to help.
