### ISSUE TITLE
CropForeground pads asymmetric 

### ISSUE THREAD

**Issue by razorx89** [Project-MONAI/MONAI#3830]
**Describe the bug**
In `CropForeground`/`CropForegroundd` the user can request a margin around the foreground voxels. However, currently the margin is only correctly padded on the upper side of a dimension.

See:
https://github.com/Project-MONAI/MONAI/blob/c3db337644d9525610d9fab3cfd30f963438dc6a/monai/transforms/utils.py#L924-L926

**To Reproduce**
```python
from monai.transforms import CropForeground
import numpy as np

transform = CropForeground(margin=2)
arr = np.eye(3)[np.newaxis, ...]
for i in range(3):
    inp = arr[:, i]
    res = transform(inp)
    print(inp, res.shape)
# [[1. 0. 0.]] (1, 3)
# [[0. 1. 0.]] (1, 4)
# [[0. 0. 1.]] (1, 5)
```

**Expected behavior**
The specified margin should be enforced by cropping or padding on both ends of a dimension. 

**Environment**
Monai 0.8.0, but see Permalink above

**Comment by Nic-Ma** [comment]
Hi @razorx89 ,

Thanks for your feedback, let me verify locally and get back to you soon.

**Comment by wyli** [comment]
the docstring is also incorrect https://github.com/Project-MONAI/MONAI/blob/b0f70e290f0441a78ef9fb760acf1089575bd24c/monai/transforms/utils.py#L895

**Comment by Nic-Ma** [comment]
The root cause is that: when we developed this transform, the `margin` was defined to align with image edges and actually the logic is wrong, it only checks left side.
After adding `crop_pad` and `k_divisible` support, the `margin` can support not to align with image edges.
So I clearly enhanced the logic to fix it in PR https://github.com/Project-MONAI/MONAI/pull/3837.

Thanks.
