### ISSUE TITLE
Including tiles coordinates in TileOnGrid transform

### ISSUE THREAD

**Issue by vale-salvatelli** [Project-MONAI/MONAI#4090]
Hi MONAI team! Here a feature request concerning Pathology that would really help us.

**Problem description:**
- My team would like to develop a deepmil pipeline where WSI **slides are tiled on the fly** reusing as much components as possible from MONAI. 
- [TileOnGrid](https://docs.monai.io/en/stable/_modules/monai/apps/pathology/transforms/spatial/array.html) is the transform currently offered by the library and suggested in the [tutorial](https://github.com/Project-MONAI/tutorials/blob/master/pathology/multiple_instance_learning/panda_mil_train_evaluate_pytorch_gpu.py) for this task. 
- The problem we encountered is that **this transformation does not return the coordinates of the tiles**. This makes impossible to reconstruct model outputs that depends on the coordinates, such as attention maps. 
- Attention maps are an essential tool for model interpretation. 

**Suggested feature:**
A transformation having all the options in TileOnGrid (e.g. random offset, randomized tiles selection, overlapping tiles) that returns also the tiles coordinates with respect to a fixed reference system (e.g. top corner of the slide).

**Alternative solution**
One alternative solution is not to tile on the fly. Pre-tiling comes however with other drawbacks: it requires extensive pre-processing, reloading files in memory and overall it offers less modelling flexibility because the tiling parameters cannot be model parameters.

**Comment by Nic-Ma** [comment]
Hi @vale-salvatelli ,

Thanks very much for your interest and feedback here.
@drbeh @myron What do you think about it? Could you please help share some comments?

Thanks in advance.

**Comment by drbeh** [comment]
Hi @vale-salvatelli, that's a great point! Thanks!
Let me think about it and come back to you. Until prioritizing this feature, I will add it to the backlog of MOANI Pathology.

**Comment by vale-salvatelli** [comment]
Thanks all for the speedy reply. @drbeh looking forward to hear what you think

**Comment by Nic-Ma** [comment]
Hi @drbeh ,

In my simple mind, I feel maybe you can refer to the GridPatch as an example of `patch` & `coordinate` outputs:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/utils.py#L220

Thanks.

**Comment by drbeh** [comment]
Thank you @Nic-Ma for your suggestion. 

One point that we need to consider here is that, unlike radiology images, `patch` (tile or regions a native concepts in whole slide imaging, and we can make this process much simpler. Here is my thinking and approach to address this issue:
1. Given a coordinate, a single patch handling (like loading and padding) is being handled by `WSIReader` via its backend libraries like OpenSlide and cuCIM.
2. Its duty of `WSIReader` to return the information about the patches when relying on it for patching. #4098 
3. Then for this scenario (extract patches directly from WSI), it makes sense to delegate the task of generating random patches to a dataset. So we can implement a `RandomPatchWSIDataset` (in addition to `PatchWSIDataset`), which generate and extract random patches from whole slide images. #4099
4. On the other hand, if patching is being done for an image in the memory rather than on the file system, the process becomes similar to other applications in MONAI. However, for specifically for `TileOnGrid`, we can track the location of all patches and returning the list of locations corresponding to each patch as a metadata in the transform call.
@vale-salvatelli, can this solution solve your issue?

Anyways, we are refactoring `GridOnTile` for the future release and if there is anything in this transform that can make your use case easier to implement, we would love to hear.

**Comment by Nic-Ma** [comment]
Hi @drbeh ,

Thanks for your proposal, it overall looks good to me to put the random logic in a dataset.
And I think maybe you can refer to the existing `GridPatchDataset`:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/grid_dataset.py#L134
@wyli @ericspod What do you think?

Thanks.

**Comment by ericspod** [comment]
What we've done in other areas of MONAI is have random patch selection done by transforms like `RandSpatialCrop`. Unless there's a specific need to have a randomised dataset I would avoid this since it breaks from that existing architectural choice.

**Comment by drbeh** [comment]
> What we've done in other areas of MONAI is have random patch selection done by transforms like `RandSpatialCrop`. Unless there's a specific need to have a randomised dataset I would avoid this since it breaks from that existing architectural choice.

Hi @ericspod, thanks for your feedback. Unfortunately, these logics do not work in digital pathology where we are dealing with whole slide imaging (WSI). Here we do not load the entire image to memory so that we can randomly crop or extract patches in the transforms, instead we load a specific patch from WSI in data loading part. Thus, the randomness needs to be appear in the datasets. Does it make sense?

**Comment by vale-salvatelli** [comment]
Thank you @drbeh for your thoughts

> 3. Then for this scenario (extract patches directly from WSI), it makes sense to delegate the task of generating random patches to a dataset. So we can implement a `RandomPatchWSIDataset` (in addition to `PatchWSIDataset`), which generate and extract random patches from whole slide images. [Whole slide dataset to extract random patches #4099](https://github.com/Project-MONAI/MONAI/issues/4099)
This is an interesting idea. We could integrate this `RandomPatchWSIDataset` in our pipeline if available. The important thing is that in this case the item returned by the dataset includes the coordinates.

> 4. On the other hand, if patching is being done for an image in the memory rather than on the file system, the process becomes similar to other applications in MONAI. However, for specifically for `TileOnGrid`, we can track the location of all patches and returning the list of locations corresponding to each patch as a metadata in the transform call.
>    @vale-salvatelli, can this solution solve your issue?
Returning as metadata would probably work. `TileOnGrid` could also maybe be a `MapTransform` and operate/return a dict where one field are the locations? I think an aspect that is important to keep in mind is the integration with other transforms. Usually, `TileOnGrid` is the first, after `LoadTilesBatchd` of a series of transformations/augmentations we want to apply.

**Comment by ericspod** [comment]
> 



> > What we've done in other areas of MONAI is have random patch selection done by transforms like `RandSpatialCrop`. Unless there's a specific need to have a randomised dataset I would avoid this since it breaks from that existing architectural choice.
> 
> Hi @ericspod, thanks for your feedback. Unfortunately, these logics do not work in digital pathology where we are dealing with whole slide imaging (WSI). Here we do not load the entire image to memory so that we can randomly crop or extract patches in the transforms, instead we load a specific patch from WSI in data loading part. Thus, the randomness needs to be appear in the datasets. Does it make sense?

I see what the issue is in terms of memory or other constraints. I would still suggest that the functionality shouldn't be in the dataset object itself, which should be a simple store of what files to load, and so the task of loading a patch is in the `WSIReader` as it looks like you're proposing in the redesign PR. The task of selecting what patch to load could be done in a separate transform that comes before the image loader and adds patch information to the transform dictionary (so this wouldn't work for the standard array transforms quite yet). This keeps the separation between the dataset defining what to load, a transform to generate patch information, and the reader to actually do the loading. I like keeping things separated like this but if it's getting too complex the value is lost, in which case I would go with your idea of putting patch selection into the dataset.

**Comment by drbeh** [comment]
@ericspod I see your point! The only issue is that makes it more complicated is that some information about the whole slide images (like getting metadata or loading images at lower resolution) to be able to define what patches to load (randomly). I found the implementation of this concept easier to implement in a dataset. 

Also, in digital pathology, images are usually patches and not the whole slides, so the data to load are the patches and not necessarily the entire image.
So if your look at it form different angle, what dataloader should load is defined by dataset and transforms are suppose to process the loaded data.
