### ISSUE TITLE
Threadataloader memory allocated differently on Windows and Linux

### ISSUE THREAD

**Issue by lanslotttTT** [Project-MONAI/MONAI#4140]
when I run same code on linux and windows ,I got two memory allocate result,on linux is 65GB but on windows is almost at 81GB,why? 
![2022-04-17 11-45-42 的屏幕截图](https://user-images.githubusercontent.com/30655387/163699467-92143756-c1de-4b4e-8c76-9e01fe4aba4b.png)
![屏幕截图 2022-04-17 115356](https://user-images.githubusercontent.com/30655387/163699715-649cfe38-64e3-436c-96fc-c073e8a1678a.png)
In Linux GPU RTX3090 24GB
In Windows GPU A100 80GB
Is the size of the memory allocation related to the GPU?

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

I am not sure whether we can expect the same GPU memory usage of a PyTorch program in `linux` and `windows` platforms? Especially when they are different OS versions, CUDA driver versions, CUDA versions, PyTorch versions, etc.
Otherwise, it may be expected behavior.

Thanks in advance.

**Comment by ericspod** [comment]
There really is too many factors between these two to say what the cause is. If this happens with the ThreadDataLoader only it could be down to how things are allocated per thread which is a Pytorch or CUDA issue. ThreadDataLoader itself isn't doing anything to change behaviour other than iterate over the dataset in a different thread from the one which created the dataset and data loader objects and which does the training.

**Comment by cvlearn913** [comment]
We solved the problem that multithreading on Windows platform uses spawn() and Linux uses fork(). In spawn() mode, multiple numworkers will monopolize resources, resulting in memory overflow.Your excellent [tutorial](https://github.com/Project-MONAI/tutorials/blob/master/acceleration/fast_model_training_guide.md) has avoided the problem of numworkers. The Threaddataloader is 0

**Comment by lanslotttTT** [comment]
@cvlearn913 Thanks for your help We find the [Doc](https://pytorch.org/docs/stable/data.html?highlight=dataset)
![image](https://user-images.githubusercontent.com/30655387/168732756-175eca44-abb6-493d-8507-c2913484f7ea.png)

**Comment by Nic-Ma** [comment]
Cool, glad to see that!

Thanks.
