### ISSUE TITLE
MetaTensor.applied_operations not copied during collation

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAI#4435]
In the list_data_collate, we collate the meta, but do not yet do the same for `applied_operations`.

We also are missing a test for this, which could be added to `test_meta_tensor.test_dataloader` and `test_collate`. Should also test the decollate works as expected.

**Comment by wyli** [comment]
It seems the `applied_operations` don't require recursive (de-)collating, because a minibatch may consist of data from very different `applied_operations`, stacking each field of the operations can be too restrictive.

Currently this is a simple sequence -- closing this for now, but please feel free to reopen if needed.
https://github.com/Project-MONAI/MONAI/blob/8af801478723662fa99c2804d78995bc531ae93a/monai/data/utils.py#L416-L419
