### ISSUE TITLE
Add script API to get info of all the available bundles and details in the model-zoo

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#4948]
**Is your feature request related to a problem? Please describe.**
To help developers or users easily get the information of all the bundles in the model-zoo, it would be nice to add script APIs to get the manifest of bundles and details of the specific bundle.

Similar to the existing script APIs:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/bundle/scripts.py#L154

**Comment by yiheng-wang-nv** [comment]
According to our internal discussion, we planned to implement a new API in order to:
1) achieve all bundle names (from model zoo)
2) for a bundle, achieve its basic information, such as latest version and all versions, compressed zip file size.
3) for a bundle, get its inside information, such as references, model overview and license.

I will start to do 1) and 2) first, as for 3), I think it depends on the `README.md` and `license.txt` files inside a bundle. Therefore, to get the information, we may have the following ways:
1. grab from the model zoo repo (only the latest version).
2. grab from releases (need to download first, may take a lot of time).
3. for each bundle (all versions of all merged bundle), store its `README.md` and `license.txt files in some place.

Hi @Nic-Ma , @wyli , @zephyrie , could you please provide some advices of 3) ? Thanks!

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

I think you can complete 1 & 2 first.
For 3, I think we don't need to support it so far?
And we should never access any file in the repo source code directly, source code is only used for development.
@wyli What do you think?

Thanks.
