### ISSUE TITLE
problem for importing monai

### ISSUE THREAD

**Issue by mfarhadirad** [Project-MONAI/MONAI#5171]
hello everybody
I'm trying to use monai but when I import it this error shows up. 
"The kernel appears to have died. It will restart automatically."

I have installed it using pip install monai. and I'm using python 3.9.12.

when I use jupyter notebook extension in VS code this error shows up.
"Canceled future for execute_request message before replies were done
The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details." 

this happens even when I just write "import monai"

**Comment by KumoLiu** [comment]
Hi @mersad95zd, since Jupyter Kernels can crash for many reasons that I can't exactly tell why you're having this problem. So maybe using pip install 'monai[all]' installs all the optional dependencies. Refer to: https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies. And maybe downgrade your Python version to 3.8.13.
Hope it can help you!
Thanks!

**Comment by mfarhadirad** [comment]
Hi, KumoLiu have used this code and it is almost fixed.

import os
os.environ[‘KMP_DUPLICATE_LIB_OK’]=‘True’
import monai

**Comment by Ihssene-Brahimi** [comment]
Thank you so much @mfarhadirad it worked awesome!!
