### ISSUE TITLE
Add median image filter as a transform

### ISSUE THREAD

**Issue by dzenanz** [Project-MONAI/MONAI#5264]
**Is your feature request related to a problem? Please describe.**
One problem is explained in #3178.

**Describe the solution you'd like**
Add a median filter based on @ebrahimebrahim's [medianblur_with_gpu](https://github.com/ebrahimebrahim/abcd-registration-experiments/blob/main/medianblur_with_gpu.py?rgh-link-date=2022-10-03T16%3A21%3A07Z)

**Describe alternatives you've considered**
#3178 mentions some alternatives, such as mean filtering. Those are suboptimal for many use cases.

**Additional context**
Model it after `GaussianSmooth`: https://github.com/Project-MONAI/MONAI/blob/ef68f16dde33172b2eeae5397ac75aa717808875/monai/transforms/intensity/array.py#L1139-L1171

**Comment by ebrahimebrahim** [comment]
Note that there may be a much better approach than the filter I wrote.
- Because mine has a giant sparse kernel (size $n^6$ when the filter size is $n$), it quickly becomes unwieldy as you increase the filter size. I wonder if there is a clever way around this. I sometimes see the MONAI folks implementing 2D or 3D convolutions in terms of 1D convolutions, but I never dug into how that actually works and when it can be done. Would be good to look at how some other convolution-based transforms in MONAI are implemented.
- My implementation is 3D and really we want something that is general to any spatial dimensionality. Actually I stole mine from the Kornia project; they had a 2D median filter that worked the same way.

**Comment by wyli** [comment]
I saw a similar implementation in tensorflow https://github.com/tensorflow/addons/blob/v0.17.0/tensorflow_addons/image/filters.py#L125-L200 given pytorch's convolution is up to 3d, perhaps we can support 1/2/3d as a starting point.

for the separable approximation, it seems it's useful in practice (for 2d) https://ieeexplore.ieee.org/document/4767047, maybe we can create another feature request for it after finishing this ticket, what do you think?
