### ISSUE TITLE
Updating of the SSIM metric class to be compliable with the MS SSIM Metric

### ISSUE THREAD

**Issue by PedroFerreiradaCosta** [Project-MONAI/MONAI#5417]
https://github.com/Project-MONAI/MONAI/blob/8925e3eea656dd1c24c90db70449c44d8ca0f044/monai/metrics/regression.py#L240
I propose four changes to this class to optimise it with regards to MONAI Core code:

* Have the option to return the contrast sensitivity metric, presented in the original paper: Wang, Z., Bovik, A.C., Sheikh, H.R. and Simoncelli, E.P., 2004.
            Image quality assessment: from error visibility to structural similarity.
            IEEE transactions on image processing, 13(4), pp.600-612. -> **Sec 3.B - Eq 9**
This value is needed to calculate the MS SSIM.
* Return not only a value, but the metric across batches and channels:
Not calling .mean() below
https://github.com/Project-MONAI/MONAI/blob/8925e3eea656dd1c24c90db70449c44d8ca0f044/monai/losses/ssim_loss.py#L124
* Have the metric not depend on the Loss, optimally it could be the other way around as the Loss is itself implementing the metric. This way the loss can call the metric and return the .mean() of the metric.
https://github.com/Project-MONAI/MONAI/blob/8925e3eea656dd1c24c90db70449c44d8ca0f044/monai/metrics/regression.py#L295
* This is secondary, but it would be great to aim to have both an object and a functional implementation of the metric as it happens with other metrics in MONAI Core.

Let me know if this sounds alright and I'm happy to help implementing these changes.

**Comment by Warvito** [comment]
@danieltudosiu this might be interesting to you too

**Comment by wyli** [comment]
cc @mersad95zd @Can-Zhao @finalelement

**Comment by danieltudosiu** [comment]
For context, by extending the pytorch-ssim library we internally have implemented the following (combinations and multi-scale are excluded for clarity):
- SSIM [1][2]
- Gradient-SSIM [3]
- 3-SSIM [4]
- 4-SSIM [5]
- *-SSIM [6]

Besides our implementation, we are missing the more exotic and comples ones:
- Gaussian Blur SSIM (GB-SSIM) [7]
- Improved SSIM - Sharpness (I-SSIM-S) [8]
- Contrast Sensitivity Function SSIM (CSF-SSIM) [9]
- Complex Wavelet SSIM [10]
- Improved SSIM [11]

Furthermore, since MONAI should have de facto defaults, the SSIM class' defaults should be based on medical imaging specific recommendations from publications such as [12][13] and medical imaging tested ones like [1-6,10].


[[1] Wang, Z., Bovik, A.C., Sheikh, H.R. and Simoncelli, E.P., 2004. Image quality assessment: from error visibility to structural similarity. IEEE transactions on image processing, 13(4), pp.600-612.](https://ieeexplore.ieee.org/document/1284395)

[[2] Wang, Z., Simoncelli, E.P. and Bovik, A.C., 2003, November. Multiscale structural similarity for image quality assessment. In The Thrity-Seventh Asilomar Conference on Signals, Systems & Computers, 2003 (Vol. 2, pp. 1398-1402). Ieee.](https://ieeexplore.ieee.org/document/1292216)

[[3] Chen, G.H., Yang, C.L. and Xie, S.L., 2006, October. Gradient-based structural similarity for image quality assessment. In 2006 International Conference on Image Processing (pp. 2929-2932). IEEE.](https://ieeexplore.ieee.org/document/4107183)

[[4] Li, C. and Bovik, A.C., 2009, January. Three-component weighted structural similarity index. In Image quality and system performance VI (Vol. 7242, p. 72420Q). International Society for Optics and Photonics.](https://www.spiedigitallibrary.org/conference-proceedings-of-spie/7242/72420Q/Three-component-weighted-structural-similarity-index/10.1117/12.811821.full)

[[5] Li, C. and Bovik, A.C., 2010. Content-partitioned structural similarity index for image quality assessment. Signal Processing: Image Communication, 25(7), pp.517-526.](https://www.sciencedirect.com/science/article/pii/S0923596510000354)

[[6] Rouse, D.M. and Hemami, S.S., 2008, February. Analyzing the role of visual structure in the recognition of natural image content with multi-scale SSIM. In Human Vision and Electronic Imaging XIII (Vol. 6806, p. 680615). International Society for Optics and Photonics.](https://www.spiedigitallibrary.org/conference-proceedings-of-spie/6806/1/Analyzing-the-role-of-visual-structure-in-the-recognition-of/10.1117/12.768060.short)

[[7] Chebbi, E., Benzarti, F. and Amiri, H., 2014. An improvement of structural similarity index for image quality assessment. Journal of Computer Science, 10(2), p.353.](https://thescipub.com/abstract/10.3844/jcssp.2014.353.360)

[[8] Lee, D. and Lim, S., 2016. Improved structural similarity metric for the visible quality measurement of images. Journal of Electronic Imaging, 25(6), p.063015.](https://www.spiedigitallibrary.org/journals/journal-of-electronic-imaging/volume-25/issue-06/063015/Improved-structural-similarity-metric-for-the-visible-quality-measurement-of/10.1117/1.JEI.25.6.063015.full)

[[9] Yao, J. and Liu, G., 2018. Improved SSIM IQA of contrast distortion based on the contrast sensitivity characteristics of HVS. IET Image Processing, 12(6), pp.872-879.](https://digital-library.theiet.org/content/journals/10.1049/iet-ipr.2017.0209)

[[10] Sampat, M.P., Wang, Z., Gupta, S., Bovik, A.C. and Markey, M.K., 2009. Complex wavelet structural similarity: A new image similarity index. IEEE transactions on image processing, 18(11), pp.2385-2401.](https://ieeexplore.ieee.org/document/5109651)

[[11] Aljanabi, M.A., Hussain, Z.M., Shnain, N.A.A. and Lu, S.F., 2019. Design of a hybrid measure for image similarity: a statistical, algebraic, and information-theoretic approach. European Journal of Remote Sensing, 52(sup4), pp.2-15.](https://www.tandfonline.com/doi/full/10.1080/22797254.2019.1628617)

[[12] Renieblas, G.P., Nogués, A.T., González, A.M., León, N.G. and Del Castillo, E.G., 2017. Structural similarity index family for image quality assessment in radiological images. Journal of medical imaging, 4(3), p.035501.](https://www.spiedigitallibrary.org/journals/journal-of-medical-imaging/volume-4/issue-3/035501/Structural-similarity-index-family-for-image-quality-assessment-in-radiological/10.1117/1.JMI.4.3.035501.short?SSO=1)

[[13] Kumar, B., Kumar, S.B. and Kumar, C., 2013, December. Development of improved SSIM quality index for compressed medical images. In 2013 IEEE Second International Conference on Image Information Processing (ICIIP-2013) (pp. 251-255). IEEE.](https://ieeexplore.ieee.org/document/6707593)

**Comment by mersad95zd** [comment]
Thanks @PedroFerreiradaCosta @danieltudosiu, these are all very nice suggestions!
@wyli I'm a bit busy these days (sorry for my late reply), but will soon collaborate with @Can-Zhao to add these features.

**Comment by danieltudosiu** [comment]
@mersad95zd me and @PedroFerreiradaCosta can work with you on implementing them. Internally we have code that is well documented and is ready to be merged into MONAI core nearly. Would you be ok if we join in on working on this?

**Comment by wyli** [comment]
thanks @danieltudosiu and @PedroFerreiradaCosta, please go ahead and submit PRs, I think @mersad95zd and @Can-Zhao can help review them...

**Comment by danieltudosiu** [comment]
Another note about the wide applications of SSIM and the requirements for diverse implementations that could be present in MONAI [1].

[[1] Mudeng, V., Kim, M. and Choe, S.W., 2022. Prospects of Structural Similarity Index for Medical Image Analysis. Applied Sciences, 12(8), p.3754.](https://www.mdpi.com/2076-3417/12/8/3754/htm)
