### ISSUE TITLE
Verify pathology tumor detection bundle with monai 1.0.1 and PyTorch 1.13

### ISSUE THREAD

**Issue by drbeh** [Project-MONAI/MONAI#5472]

**Comment by yiheng-wang-nv** [comment]
hi @drbeh , this has been addressed in: https://github.com/Project-MONAI/model-zoo/pull/187
The torchscript part is not supported for 1.0.1 due to an updates of the network used, and since the incompatibility issue has been resolved in: https://github.com/Project-MONAI/MONAI/issues/5485 , the related support have be added back after the next 1.1 release.
