### ISSUE TITLE
pytorch 2: TypedStorage is deprecated

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAI#5862]
**Describe the bug**

With pytorch 2, I'm getting lots of instances of this warning:

/home/rbrown/miniconda3/envs/py3.11/lib/python3.11/site-packages/torch/_tensor.py:1287: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  ret = func(*args, **kwargs)

The only usage of `torch.storage()` is [here](https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/__init__.py#L128), so I suspect that's the problem. @wyli I see you added the code, can we do without it or modify it?

**Comment by rijobro** [comment]
Can I use `tensor.untyped_storage` instead?

**Comment by wyli** [comment]
I basically followed this method

https://github.com/pytorch/pytorch/blob/v1.13.1/torch/multiprocessing/reductions.py#L149-L150

and the expected behaviour is mainly tested here https://github.com/Project-MONAI/MONAI/blob/6803061769a2dcec5839887967b0be0f2b34ac7a/tests/test_meta_tensor.py#L523-L536 `ForkingPickler` can dump and load metatensors.

feel free to update it for the latest API
