### ISSUE TITLE
weekly-preview workflow failing

### ISSUE THREAD

**Issue by Warvito** [Project-MONAI/MONAI#5882]
**Describe the bug**
For the last 2 weeks, the weekly-preview workflow has failed to deploy a new pre-release for monai-weekly.
It is showing this message:

packaging: # >> PyPA publish to PyPI GHA: UNSUPPORTED GITHUB ACTION VERSION <<#L1
 You are using "pypa/gh-action-pypi-publish@master". The "master" branch of this project has been sunset and will not receive any updates, not even security bug fixes. Please, make sure to use a supported version. If you want to pin to v1 major version, use "pypa/gh-action-pypi-publish@release/v1". If you feel adventurous, you may opt to use use "pypa/gh-action-pypi-publish@unstable/v1" instead. A more general recommendation is to pin to exact tags or commit shas.

**Comment by wyli** [comment]
I'm looking into this, the issue is from the dependency on MetricsReloaded github
https://github.com/Project-MONAI/MONAI/blob/2d0e0214ac80d97e6585edf59ffc6eed96bcfcdb/requirements-dev.txt#L55

```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         Invalid value for requires_dist. Error: Can't have direct dependency:  
         "MetricsReloaded @                                                     
         git+https://github.com/Project-MONAI/MetricsReloaded@monai-support#egg=
         MetricsReloaded ; extra == 'metricsreloaded'"                          
```

packaging monai requires a proper pypi release of `MetricsReloaded`, see also a similar issue reported https://github.com/pypi/warehouse/issues/9404.

@csudre @brudfors 

https://github.com/Project-MONAI/MetricsReloaded/issues/35

**Comment by wyli** [comment]
the auto build is working again but before releasing v1.2, we should fix https://github.com/Project-MONAI/MetricsReloaded/issues/35 and uncomment the workaround:
https://github.com/Project-MONAI/MONAI/blob/86a06f3ac9bdf1d6a288376369c6281d86f80520/setup.cfg#L136-L138
