### ISSUE TITLE
Is bundle downloading using auth_token?

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAI#6059]
Can you confirm if download is using `auth_token`.  I see it's only used for `get_all_bundles_list`

https://github.com/Project-MONAI/MONAI/blob/dev/monai/bundle/scripts.py#L205-L215
vs
https://github.com/Project-MONAI/MONAI/blob/dev/monai/bundle/scripts.py#L466-L468

**Comment by Nic-Ma** [comment]
Hi @tangy5 @yiheng-wang-nv ,

Could you please help provide some information here?

Thanks in advance.

**Comment by tangy5** [comment]
As we discussed before, there is a rate limit for accessing the Model-Zoo. The auth_token is to get around of limiatation of "requests_get" for Zoo. I don't see `download` needs this requests. @yiheng-wang-nv , can you help confirm. 
If this is true, we can improve some experience for some end usecase, now users have to provide `auth_token` of their Github, which is not very intuitive.. I feel this is also same for other framework that access Model-Zoo. Thanks.

**Comment by yiheng-wang-nv** [comment]
Hi @SachidanandAlle , `download` does not use `auth_token` and as @tangy5 said, it is different from `get_all_bundles_list ` 's usecase.
> If this is true, we can improve some experience for some end usecase, now users have to provide auth_token of their Github, which is not very intuitive

Hi @tangy5 , do you have any suggestions? Or we can discuss in details. For users that download from webpage, there is not limitations. I'm not sure if it bothers users that call the api since the rate limit for unauthorized access may already enough.
