### ISSUE TITLE
RuntimeError: SSIMLoss 3 Channel; 2D 

### ISSUE THREAD

**Issue by a-parida12** [Project-MONAI/MONAI#6267]
**Describe the bug**
I have a 2D image of batch size =128 and channel 3. What is the correct way to use the SSIMLOss

**To Reproduce**

```python
from monai.losses.ssim_loss import SSIMLoss
criterion = SSIMLoss(spatial_dims=2)
loss = criterion(images, pred, data_range=images.max().unsqueeze(0))
# images.shape == pred.shape == torch.Size([128, 3, 64, 64])
```
In the above code, I get a `RuntimeError`.

`RuntimeError: shape '[1]' is invalid for the input of size 3`

**Comment by a-parida12** [comment]
I found the trouble in `monai.losses.ssim_loss.SSIMLoss` forward does not consider multichannel SSIM for `batch_size > 1`

<img width="1530" alt="Screenshot 2023-04-01 at 23 01 40" src="https://user-images.githubusercontent.com/23334003/229328835-89e70c4b-72f4-4968-af95-efdde81462ee.png">

The newly added line 94 & 95 is a quick hotfix around handling multichannel images. @wyli let me know if this will be solved by #6249 . Else I will be happy to contribute and push the above changes.

**Comment by wyli** [comment]
I couldn't replicate your issue, running your example I get the following error:
```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    loss = criterion(images, pred, data_range=images.max().unsqueeze(0))
NameError: name 'images' is not defined
```

**Comment by a-parida12** [comment]
Sorry was missing a line! updated code below-

```python
from monai.losses.ssim_loss import SSIMLoss
criterion = SSIMLoss(spatial_dims=2)
images = pred = torch.ones([128, 3, 64, 64]) #  torch.ones([128, 1, 64, 64]) works fine
loss = criterion(images, pred, data_range=images.max().unsqueeze(0))
```

**Comment by wyli** [comment]
I see, yes #6250 seems to fix it but it removed `data_range` from the function call, not sure if we want to support dynamic `data_range`  cc  @ericspod

**Comment by a-parida12** [comment]
Anyways the dynamic `data_range` is super trivial and could be best hidden away from the user(estimated when the function is called). Like most loss functions would allow me as an end user to call `criterion(pred, images)`

**Comment by Warvito** [comment]
In #6250, I ended up removing the dynamic `data_range` because I was not sure how much it was used. Usually, in the data transforms, we use a scaling transform to change the original intensity range of the images to a predefined range (e.g., [0.0-1.0]). So assuming a static data_range of 1.0 (for example) seemed to be an okay approach. In my view, I do not see a problem to have a argument when instanciating the loss indicating to internally use the dynamic range instead.

**Comment by ericspod** [comment]
I would say that data range normalisation should be a separate step (ie. transform). Since there are various places we would want to normalise data, keeping it in one place reduce code duplication. Here if we have a constructor parameter plus a forward call parameter to do the same thing there would be code duplication and multiple ways to do the same thing, general rule of thumb is to have one obvious way of doing something only.

**Comment by wyli** [comment]
thanks, closing with https://github.com/Project-MONAI/MONAI/commit/43902e3330da8d879222511131e60f40b38d692e
