### ISSUE TITLE
Suggestion for improving TiffFileWSIReader speed

### ISSUE THREAD

**Issue by Dylan-H-Wang** [Project-MONAI/MONAI#6513]
I have found that if I choose `tifffile` as the backend of `WSIReader` in `SlidingPatchWSIDataset`, the speed would be extremely slow if the level is set to `0`. After checking the source code, it seems like the lag mainly comes from 
https://github.com/Project-MONAI/MONAI/blob/7f3d3fc79e0caa0953f801c903368e74a65a8773/monai/data/wsi_reader.py#L1150-L1188
where each call of this function will load the whole `WSI` into memory and only take portion of it based on the input `location`. This is really inefficient compared with `cucim` and `openslide`.

I am thinking it would be good to add an option `fast_tiff` to indicate whether user wants more memory efficiency or time efficiency. By setting `fast_tiff=True`, the `WSI` at `level=0` will be loaded and stored into memory, and each call to `get_data` can directly reference to this variable instead of using `asarray(level=level).astype(dtype)` every time.

For example:
```python
# somewhere
self.wsi = wsi_tiff_object.asarray(level=level).astype(dtype)

def _get_patch(
    self, wsi, location: tuple[int, int], size: tuple[int, int], level: int, dtype: DtypeLike, mode: str
) -> np.ndarray:
    # Load the entire image
    wsi_image: np.ndarray = self.wsi

    .... # unchaned lines
```

**Comment by drbeh** [comment]
Hi @Dylan-H-Wang, thank for you suggestion. Caching the entire image is a wise idea. However, it can become problematic in many training use cases if user is not aware of it. For instance, it is very common to load patches from different WSI images randomly for training, e.g. patch_1 from WSI_1, patch_2 from WSI_2, patch_3 from WSI_10, patch_4 from WSI_5 etc. So it means to load all the WSIs into memory, which makes the user's code to crash due to OOM.

Having said that, your suggestion would be beneficial for inference purposes where we usually exhaust a WSI before moving to the next. We should see how to handle this caching effectively. For instance, what should be the criteria to release this cache and cache another WSI? Should it have specific cache size?

Currently, TiffFile is not a preferrer backend if you want to deal with extracting random patches (and not the entire image) from WSI since we can efficiently do that using openslide or cucim  backend. Also for inference purposes if the user has sufficient memory, they can load the entire image first and use GridPatch to split the image into patches for instance.

Although you are more than welcome to implement this caching and we will help you to improve it and guide you in the way of contributing to MONAI, it would be great if you can explain more about your use case so we can find the best way to address it.

**Comment by Dylan-H-Wang** [comment]
> Hi @Dylan-H-Wang, thank for you suggestion. Caching the entire image is a wise idea. However, it can become problematic in many training use cases if user is not aware of it. For instance, it is very common to load patches from different WSI images randomly for training, e.g. patch_1 from WSI_1, patch_2 from WSI_2, patch_3 from WSI_10, patch_4 from WSI_5 etc. So it means to load all the WSIs into memory, which makes the user's code to crash due to OOM.
> 
> Having said that, your suggestion would be beneficial for inference purposes where we usually exhaust a WSI before moving to the next. We should see how to handle this caching effectively. For instance, what should be the criteria to release this cache and cache another WSI? Should it have specific cache size?
> 
> Currently, TiffFile is not a preferrer backend if you want to deal with extracting random patches (and not the entire image) from WSI since we can efficiently do that using openslide or cucim backend. Also for inference purposes if the user has sufficient memory, they can load the entire image first and use GridPatch to split the image into patches for instance.
> 
> Although you are more than welcome to implement this caching and we will help you to improve it and guide you in the way of contributing to MONAI, it would be great if you can explain more about your use case so we can find the best way to address it.

Thank you for the reply and explanation!

I agree that caching many huge WSIs into the memory is a problematic operation. In my case, the situation is some pathology datasets provide segmentation masks in `tiff` format and they do not have `channel_dim`, i.e., the mask shape is `(HxW)`. This format is not compatible for `CuCim` backend and thus I have to use `tifffile` as the backend to extract mask patches. In my implementation (I am extracting patches to build dataset), since I only read a single WSI every time and thus it is feasible for me to load the whole mask into the memory although I still use `CuCim` to load WSI images.
