### ISSUE TITLE
Cannot get mpp info with 'openslide' backend.

### ISSUE THREAD

**Issue by ChenglongWang** [Project-MONAI/MONAI#6520]
**Describe the bug**
I tried to use 'openslide' as my backend to get 'mpp' info from pathology data (tiff and mrxs format), `KeyError` exception was thrown. It appears that the wsi instance does not contain the keys "tiff.YResolution" and "tiff.XResolution".  I don't know why openslide_reader is using "tiff.XResolution" tag to get the resolution instead of "openslide.mpp-x" tag.

**To Reproduce**
Here is my code example:
```
from monai.data import wsi_reader

image = "/path_to_tif_data/2019_01450.tif"
image = "/path_to_mrxs_data/18_15112.mrxs"  #! mrxs format also not work

reader = wsi_reader.WSIReader("openslide", level=0)
wsi = reader.read(image)
reader.get_mpp(wsi)  #! throw KeyError

print(wsi.properties["openslide.mpp-x"], wsi.properties["openslide.mpp-y"])  #! return (0.467084 0.467084), looks fine
```

**Environment**

MONAI version: 1.1.0
Numpy version: 1.23.5
Pytorch version: 1.12.1
openslide version: 3.4.1
openslide-python: 1.2.0

**Comment by KumoLiu** [comment]
Hi @drbeh, could you please take a look at this issue and share some comments, thanks in advance!

**Comment by drbeh** [comment]
Hi @ChenglongWang, thanks for reporting this issue. We will take a look into it and will keep you posted.

**Comment by drbeh** [comment]
Hi @ChenglongWang, I looked into this problem and it seems that this issue has been fixed in the newer version of MONAI, and it uses `openslide.mpp-x` and `openslide.mpp-y` if they exist. It only fall back to use tiff metadata if those openslide tags do not exit.
MONAI v1.2 is not out there yet but you can use `monai-weekly` to have your problem fix. Can you please try it and let us know if it is resolved?

https://github.com/Project-MONAI/MONAI/blob/8e725aa2f3c50ffd1c0c45e8917d85f20c6637d0/monai/data/wsi_reader.py#L913-L922

**Comment by ChenglongWang** [comment]
@drbeh @KumoLiu Thank you for your quick response. The issue has been solved in the latest dev version.
