### ISSUE TITLE
lazy `RandAffine` has no effect

### ISSUE THREAD

**Issue by function2-llx** [Project-MONAI/MONAI#6773]
**Describe the bug**
When using `RandAffine` with `lazy=True`, it does not perform any transform at all.

**To Reproduce**
```python
import torch

from monai import transforms as mt

def main():
    x = torch.randn(1, 32, 32, 32)
    trans = mt.Compose(
        [mt.RandAffine(1., translate_range=[(0, 0), (1, 1), (2, 2)])],
        lazy=False
    )
    print(trans(x).affine)
    lazy_trans = mt.Compose(
        [mt.RandAffine(1., translate_range=[(0, 0), (1, 1), (2, 2)])],
        lazy=True,
    )
    print(lazy_trans(x).affine)

if __name__ == '__main__':
    main()
```

**Actual Result**
```plain
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 1.],
        [0., 0., 1., 2.],
        [0., 0., 0., 1.]], dtype=torch.float64)
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]], dtype=torch.float64)
```

**Comment by wyli** [comment]
thanks for testing and reporting @function2-llx, that's a good point, the bug was not detected earlier because we used the same transform instance to verify lazy/non-lazy consistency in this case https://github.com/Project-MONAI/MONAI/blob/e2fa53b614f1257df6034f6a2e5de288e8d85ba8/tests/test_rand_affine.py#L145-L148, your PR #6774 addresses the issue, I'll try to make it backward compatible (in terms of pseudo random states) and merge it.
