### ISSUE TITLE
ImportError: cannot import name 'normal_init' from 'monai.networks'

### ISSUE THREAD

**Issue by carlpe** [Project-MONAI/MONAI#684]
Trying the GAN tutorial for mednist. 

Getting following error: 

> ImportError                               Traceback (most recent call last)
>  in 
>      19     Transform, Compose, AddChannel, ScaleIntensity, ToTensor, RandRotate, RandFlip, RandZoom
>      20 from monai.networks.nets import Generator, Discriminator
> ---> 21 from monai.networks import normal_init
>      22 from monai.utils import progress_bar
>      23 
> 
> ImportError: cannot import name 'normal_init' from 'monai.networks' (C:\Users\carlk\Anaconda3\envs\monai\lib\site-packages\monai\networks\__init__.py)

**Environment (please complete the following information):**
 - OS : Win10
 - Python version: 3.7.7 64bit
 - MONAI version monai-0.2.0rc3+14.g640852a.dist-info
 - CUDA/cuDNN version 10.2 / 7.6

**Comment by Nic-Ma** [comment]
Hi @carlpe ,

Thanks for your bug report. We just updated this tutorial today according to the latest API.
Could you please help try to use the latest MONAI source code and try again?
Or you can change branch to 0.2.0rc3 and use the tutorial code in that branch.

Thanks.

**Comment by carlpe** [comment]
Yes, I will try it tomorrow, and report back to you

-Carl

**Comment by carlpe** [comment]
The good news is that the error disappeared once I updated to the latest code (tag d5e56ab0).

The bad news is that a new error appeared further down, illustrated in the below screenshot. 

![Untitled](https://user-images.githubusercontent.com/54416001/86441831-1c956a00-bd0d-11ea-9a05-c73ba4410d65.png)

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

Could you please help take a look at this issue in the GAN notebook?
Thanks in advance.

**Comment by wyli** [comment]
I think this is a known issue of multi-processing on Windows, we had a workaround for the example scripts https://github.com/Project-MONAI/MONAI/pull/307, might be difficult to realise it in the notebooks. A quick fix would be setting num_workers to 0

**Comment by carlpe** [comment]
Setting num_worker = 0 did work here.

However it is not utilizing the GPU.

**Comment by ericspod** [comment]
This is indeed an issue with multiprocessing in Windows because we don't have fork semantics and other things that are present in Unix-like environments. The way Python gets around this is to create new processes which imports parent code as module, this relies on "if __name__ == '__main__':" blocks in the start script preventing setup code being called in the child since __name__ won't be __main__ in that case. With fork semantics the pipes and other multiprocessing objects will be shared between parent and child, with Windows these need to be communicated explicitly from parent to child which doesn't appear to be happening here.

**Comment by wyli** [comment]
@ericspod  thanks for the detailed explanations!
