### ISSUE TITLE
Update the schema for MONAI Bundle

### ISSUE THREAD

**Issue by KumoLiu** [Project-MONAI/MONAI#7303]
There are several things we want to update in the schema.
https://github.com/Project-MONAI/MONAI-extra-test-data/releases/download/0.8.1/meta_schema_20220324.json

- Rename `optional_packages_version` to `required_packages_version`, https://github.com/Project-MONAI/MONAI/pull/7253
- Differentiate between model output and postprocessing output, https://github.com/Project-MONAI/MONAI/issues/6724
- Take into account other types in network's forward pass, https://github.com/Project-MONAI/MONAI/issues/6959#issuecomment-1825965246

**Comment by ericspod** [comment]
Points about this schema:
* A lot of the structural description was moved to `$defs` for reuse. This is the clean way of doing things it seems with `$comment` keys for comment information pertaining to the schema only.
* With `"patternProperties": { "^[_a-zA-Z0-9]+_data_format$": { "$ref": "#/$defs/network_io" }},`  the schema now permits multiple network definitions to be included based on the naming pattern, so a network called `foo` in any of the scripts is specified with `foo_data_format`. This is different from what we had thought of before of having one bundle per network. 
* This schema validates against all the existing model zoo models except for 2 recent generative models which don't have a `network_data_format` field. This could be fixed with a rename of the networks in those bundles or by removing `network_data_format` from the schema and relying on the pattern property instead (but this would allow schemas without any data format). 
* The CI/CD checks in the model zoo should enforce this schema using the `jsonschema` package and a simple script to check every schema and ensure there's at least one `*_data_format` value.
* We can also add scripts to format all json and yaml files automatically, I have simple versions for these two tasks that produces a slightly more compact result for both than is typically done.

**Comment by ericspod** [comment]
Both `required_packages_version` and `optional_packages_version` fields are required, the current model zoon metadata.json files will validate as said except for the absense of `required_packages_version`.

**Comment by KumoLiu** [comment]
> Both `required_packages_version` and `optional_packages_version` fields are required, the current model zoon metadata.json files will validate as said except for the absense of `required_packages_version`.

Since we already know all of the packages we need after the bundle was created, we could remove 'optional_packages_version', which may be confusing, and instead, directly use 'required_packages_version'. What do you think? cc @Nic-Ma

**Comment by KumoLiu** [comment]
> This is different from what we had thought of before of having one bundle per network.

So do we currently have such a need to add multiple networks in a bundle?
It seems generative models have such requirements.
https://github.com/Project-MONAI/model-zoo/blob/e99e61aeb6fd21fc8613fd6099463ca8d7420aca/models/brats_mri_axial_slices_generative_diffusion/configs/metadata.json#L33

> This could be fixed with a rename of the networks in those bundles or by removing network_data_format from the schema and relying on the pattern property instead (but this would allow schemas without any data format).

Instead of renaming and replying on the pattern property, I think these two generative models missing the `network_data_format`, so we should add them. `network_data_format` should still be a required field.
https://github.com/Project-MONAI/model-zoo/blob/e99e61aeb6fd21fc8613fd6099463ca8d7420aca/models/brats_mri_axial_slices_generative_diffusion/configs/train_diffusion.json#L18C6-L18C17

**Comment by KumoLiu** [comment]
Hi @ericspod, thanks for the new schema you updated, I agree with the idea of `$defs` for reuse.
We may need more people to help review the updated schema, would you mind creating a draft PR so that people can easily leave comments?

**Comment by ericspod** [comment]
I've made the PR #7409 but I don't know if we want the schema to be here. The schema lives in a release storage data [here](https://github.com/Project-MONAI/MONAI-extra-test-data/releases/tag/0.8.1) rather than in a repository.
