### ISSUE TITLE
Necessary precautions for CuCIM updates

### ISSUE THREAD

**Issue by drbeh** [Project-MONAI/MONAI#7452]
CuCIM is a dependency of MONAI for efficiently loading whole slide images and also some GPU accelerated transforms that are being accessed via `CuCIM` transform in MONAI.

CuCIM has dropped the support for Python 3.8 in the latests versions while MONAI is still supporting it. Currently, the version that we are using in MONAI is `cucim==23.10.0` (the latest available on PyPI for this specific package) which supports Python 3.8. However, in order to be able to upgrade to the latest version (which is under different package name), we should first make sure that these CuCIM updates does not affect MONAI functionalities, especially our CI/CD.

**Comment by drbeh** [comment]
@ericspod @KumoLiu @wyli @aylward

**Comment by aylward** [comment]
My thoughts...

Python 3.8 hits end-of-life in Oct, 2024; so we should discuss if we should continue to support it after that time. 

If we drop support for 3.8, there will be a branch that uses the new (renamed) CuCIM package (and has other 3.8 changes in it), and perhaps the Pathology WG can test it in their applications (as real-world tests beyond the CuCIM tests in core).  Or did you have something else in mind?

If we don't drop support for 3.8, then perhaps the old CuCIM and the newly renamed version could become optional dependencies - but that should be an exceptional/rare/temporary solution, since testing combinations of optional packages quickly becomes problematic.

Do you think this is something that needs to be addressed for the next release or before Oct 2024?

**Comment by KumoLiu** [comment]
We have dropped python 3.8 support here: https://github.com/Project-MONAI/MONAI/pull/7909
And also add cucim-cu12 as a dependency here: https://github.com/Project-MONAI/MONAI/blob/dev/requirements-dev.txt#L29

Closing this ticket for now.
