### ISSUE TITLE
Consideration of Flash Attention in Generative Components

### ISSUE THREAD

**Issue by KumoLiu** [Project-MONAI/MONAI#7944]
Regarding the comments here: https://github.com/Project-MONAI/MONAI/pull/7715#issuecomment-2088149866

We have removed the flash attention from the generative components merged into the core. However, based on experiments conducted by @dongyang0122, there appears to be a significant difference between using and not using flash attention. We should consider adding this option back. @dongyang0122 will share more detailed comparison results from the experiments.

**Comment by KumoLiu** [comment]
cc @ericspod @virginiafdez

**Comment by dongyang0122** [comment]
We use the following Python script for comparison. When flash attention is enabled, we are able to train the diffusion model with batch size 1. When flash attention is disabled, the training process will cause out of memory.

[verify_training.py.txt](https://github.com/user-attachments/files/16370245/verify_training.py.txt)

**Comment by mingxin-zheng** [comment]
Thanks @dongyang0122 for the verification.

It seems to me that xformers/flash_attention brought benefits and we should weight including them in the dependency list.

On the other hand, installation of the package could be challenging, because the range of  `torch`, `cuda`, and os platform seems narrow: https://github.com/facebookresearch/xformers/issues

If `monai` leaves the installation of `xformers` to the user but we keep the `optional_import` in the code base, is this acceptable?

**Comment by ericspod** [comment]
We could look at using the flash attention in Pytorch as well: https://pytorch.org/blog/pytorch2-2/

**Comment by KumoLiu** [comment]
Thanks to @dongyang0122 for the script. I tried the script and tested it on both the original generative implementation and the PyTorch implementation. The results are shown below. We can see that PyTorch almost achieves the same results as the xformer implementation. Based on this, I believe we can use PyTorch instead.

![image](https://github.com/user-attachments/assets/31deb9ba-4c6b-4c70-a791-7296a6cd44a9)

**Comment by KumoLiu** [comment]
cc @guopengf for vis. Here is the code I use: https://github.com/KumoLiu/MONAI/tree/flash-atten
