### ISSUE TITLE
Remove gdown dependency

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#935]
**Is your feature request related to a problem? Please describe.**
As we already moved Decathon dataset from Google drive to AWS, no need to use gdown.
Need to remove all the gdown dependency as a optional import.

see also https://github.com/Project-MONAI/MONAI/issues/915

**Comment by ericspod** [comment]
We should have everything hosted in one place, ie. AWS, so we should migrate everything there. For other things which can be downloaded via URL we could keep if need be, I think even gdrive files can be had through URLs so gdown seems doubly unneeded.

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

Thanks for your comments.
@wyli  what do you think? should we remove `gdown` now or leave it for v0.4 or any necessary concern to keep it?

Thanks.

**Comment by wyli** [comment]
currently `monai.utils.download_url`will automatically try to use gdown if it's a google drive link, this is completely optional and not tightly coupled with the rest of monai functionality. I feel this might be helpful for the users to build some quick/lightweight demo? we could keep this minimal feature and add some lightweight unit tests for this function? (releasing via AWS open data requires quite some paperwork and the proposal review might be slow https://aws.amazon.com/opendata/open-data-sponsorship-program/)

but I also agree that from our side we shouldn't rely on this feature to build our demos/examples/core features because the google drive has some limitations.

**Comment by rijobro** [comment]
https://github.com/Project-MONAI/MONAI/blob/52e254ff3a87ccdd4c5d14c3a01b9d9fe5f9c855/monai/apps/utils.py#L80-L82

Unless I've misunderstood, if the link is a google drive, then `gdown` is used (i.e., it is not optional). 

Presumably, this:
```
if url.startswith("https://drive.google.com"):
```
should be:

```
if url.startswith("https://drive.google.com") and has_gdown:
```

**Comment by Nic-Ma** [comment]
OK, let's keep `gdown` for a while.
Remove my ARB.

Thanks.

**Comment by wyli** [comment]
thanks @Nic-Ma, I'm closing this ticket with https://github.com/Project-MONAI/MONAI/pull/946 merged, please feel free to reopen if needed
